# Configure Air code formatter
# https://posit-dev.github.io/air/configuration.html

# Use default settings in an empty config file.
# https://posit-dev.github.io/air/configuration.html#configuration-recommendations
